//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicoLauncher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicoLauncher.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Completed {
            get {
                return ResourceManager.GetStream("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.txt.
        /// </summary>
        internal static string ConfigurationFilename {
            get {
                return ResourceManager.GetString("ConfigurationFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - DESTINATION FOLDER (DSPICO).
        /// </summary>
        internal static string Dest {
            get {
                return ResourceManager.GetString("Dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dspico_Image_logo {
            get {
                object obj = ResourceManager.GetObject("dspico_Image_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon dspico_logo {
            get {
                object obj = ResourceManager.GetObject("dspico_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force file overwrite.
        /// </summary>
        internal static string Forced_File_Overwrite {
            get {
                return ResourceManager.GetString("Forced_File_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Home {
            get {
                return ResourceManager.GetStream("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open destination on completion.
        /// </summary>
        internal static string Open_dest_on_completetion {
            get {
                return ResourceManager.GetString("Open_dest_on_completetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - SOURCE COVER FOLDER.
        /// </summary>
        internal static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Remove {
            get {
                return ResourceManager.GetStream("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Covers Without ROM Detected.
        /// </summary>
        internal static string RomCoverCleanup {
            get {
                return ResourceManager.GetString("RomCoverCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - ROMS FOLDER (CLEANUP MODE).
        /// </summary>
        internal static string Roms_Folder_Cleanup_mode {
            get {
                return ResourceManager.GetString("Roms_Folder_Cleanup_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Select {
            get {
                return ResourceManager.GetStream("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START PROCESS.
        /// </summary>
        internal static string Start_Process {
            get {
                return ResourceManager.GetString("Start_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM READY.
        /// </summary>
        internal static string System_Ready {
            get {
                return ResourceManager.GetString("System_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSPico Converter v4.2.
        /// </summary>
        internal static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rikisoft 2026.
        /// </summary>
        internal static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
    }
}
